#############################################################################
# Makefile for building: ImageCrop
# Generated by qmake (2.01a) (Qt 4.8.5) on: ?? 8? 25 15:22:16 2013
# Project:  ImageCrop.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -o Makefile ImageCrop.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1,--sort-common,--as-needed,-z,relro -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		settingdialog.cpp \
		mainview.cpp \
		resizedialog.cpp moc_mainwindow.cpp \
		moc_settingdialog.cpp \
		moc_mainview.cpp \
		moc_resizedialog.cpp \
		qrc_ImageCrop.cpp
OBJECTS       = main.o \
		mainwindow.o \
		settingdialog.o \
		mainview.o \
		resizedialog.o \
		moc_mainwindow.o \
		moc_settingdialog.o \
		moc_mainview.o \
		moc_resizedialog.o \
		qrc_ImageCrop.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		ImageCrop.pro
QMAKE_TARGET  = ImageCrop
DESTDIR       = 
TARGET        = ImageCrop

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_settingdialog.h ui_resizedialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ImageCrop.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile ImageCrop.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile ImageCrop.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/ImageCrop1.0.0 || $(MKDIR) .tmp/ImageCrop1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/ImageCrop1.0.0/ && $(COPY_FILE) --parents mainwindow.h settingdialog.h mainview.h resizedialog.h .tmp/ImageCrop1.0.0/ && $(COPY_FILE) --parents ImageCrop.qrc .tmp/ImageCrop1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp settingdialog.cpp mainview.cpp resizedialog.cpp .tmp/ImageCrop1.0.0/ && $(COPY_FILE) --parents mainwindow.ui settingdialog.ui resizedialog.ui .tmp/ImageCrop1.0.0/ && $(COPY_FILE) --parents zh_CN.ts .tmp/ImageCrop1.0.0/ && (cd `dirname .tmp/ImageCrop1.0.0` && $(TAR) ImageCrop1.0.0.tar ImageCrop1.0.0 && $(COMPRESS) ImageCrop1.0.0.tar) && $(MOVE) `dirname .tmp/ImageCrop1.0.0`/ImageCrop1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/ImageCrop1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_settingdialog.cpp moc_mainview.cpp moc_resizedialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_settingdialog.cpp moc_mainview.cpp moc_resizedialog.cpp
moc_mainwindow.cpp: mainview.h \
		mainwindow.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_settingdialog.cpp: settingdialog.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) settingdialog.h -o moc_settingdialog.cpp

moc_mainview.cpp: mainview.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) mainview.h -o moc_mainview.cpp

moc_resizedialog.cpp: resizedialog.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) resizedialog.h -o moc_resizedialog.cpp

compiler_rcc_make_all: qrc_ImageCrop.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_ImageCrop.cpp
qrc_ImageCrop.cpp: ImageCrop.qrc \
		qt_zh_CN.qm \
		zh_CN.qm \
		images/crop.png \
		images/cut.png \
		images/quit.png \
		images/resize.png \
		images/slice.png \
		images/open.png
	/usr/lib/qt4/bin/rcc -name ImageCrop ImageCrop.qrc -o qrc_ImageCrop.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_settingdialog.h ui_resizedialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_settingdialog.h ui_resizedialog.h
ui_mainwindow.h: mainwindow.ui
	/usr/lib/qt4/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_settingdialog.h: settingdialog.ui
	/usr/lib/qt4/bin/uic settingdialog.ui -o ui_settingdialog.h

ui_resizedialog.h: resizedialog.ui
	/usr/lib/qt4/bin/uic resizedialog.ui -o ui_resizedialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		mainview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		mainview.h \
		ui_mainwindow.h \
		settingdialog.h \
		resizedialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

settingdialog.o: settingdialog.cpp settingdialog.h \
		ui_settingdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settingdialog.o settingdialog.cpp

mainview.o: mainview.cpp mainview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainview.o mainview.cpp

resizedialog.o: resizedialog.cpp resizedialog.h \
		ui_resizedialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o resizedialog.o resizedialog.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_settingdialog.o: moc_settingdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_settingdialog.o moc_settingdialog.cpp

moc_mainview.o: moc_mainview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainview.o moc_mainview.cpp

moc_resizedialog.o: moc_resizedialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_resizedialog.o moc_resizedialog.cpp

qrc_ImageCrop.o: qrc_ImageCrop.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_ImageCrop.o qrc_ImageCrop.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

